name: 01 - Building Blocks

on:
  workflow_dispatch:

jobs:
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World"
      - name: Failed Step
        run: echo "i will fail"
      - name: Say goodbye
        run: echo "Goodbye"

      - name: Multiline-batch
        run: |
          echo "I am"
          echo "a multi-line"
          echo "script."
