name: 06 - Contexts
env:
  MY_WORKFLOW_VAR: 'workflow'
  MY_OVERWRITTEN_VAR: 'workflow'
on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}
jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display context information
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          MY_JOB_VAR: 'job'
          MY_OVERWRITTEN_VAR: 'job'
        run: echo ${{ env.GITHUB_CONTEXT }}
      - name: Retrieve variable
        env:
          MY_VAR: "Hello world"
        run: echo "$MY_VAR"

      - name: Display job information
        env:
          GITHUB_JOB: ${{ toJson(job) }}
        run: echo "${{ env.GITHUB_JOB }}"
      - name: Display runner information
        env:
          GITHUB_RUNNER: ${{ toJson(runner) }}
        run: echo "${{ env.GITHUB_RUNNER }}"
      - name: Display inputs information
        env:
          GITHUB_INPUTS: ${{ toJson(inputs) }}
        run: echo "$GITHUB_INPUTS"
      - name: Print Env Variables
        env:
          MY_OVERWRITTEN_VAR: 'step'
        run: |
          echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
          echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"
