name: 14 - Working with Artifacts

on:
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 14-artifacts/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Download cached dependencies
        id: cache
        uses: actions/cache@v6
        with:
          key: deps-node-modules-${{ hashFiles('14-artifacts/react-app/package-lock.json') }}
          path: 14-artifacts/react-app/node_modules
      - name: Install dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true'}}
        run: npm ci


