name: 15 - Working with Matrices

on:
 workflow_dispatch:

jobs:
  backwards-compatibility:
    name: ${{ matrix.os }}-${{ matrix.node }}
    strategy:
      fail-fast: true
      matrix:
        node: [24.x, 26.x]
        os:
          - ubuntu-latest
          - windows-latest
        include:
          - os: ubuntu-latest
            node: 25.x
          - os: ubuntu-latest
            node: 26.x
            tag: experimental
          - os: ubuntu-latest
            node: 26.x
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node }}
      - name: Fail if experimental
        if: matrix.tag == 'experimental'
        run: exit 1
      - name: Perform some tests
        shell: bash
        run: |
          echo "Running tests on OS ${{matrix.os}} and NodeJS ${{ matrix.node}}"
          sleep 10
      - name: Upload test results
        run: echo "Uploading test results"
  include-example:
    name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        color:
          - red
          - green
        shape:
          - circle
          - square
        size:
          - small
          - large
        include:
          - color: red
            shape: triangle
    steps:
      - name: Dummy step
        run: echo "${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size}}"




